# Generated by Django 5.1 on 2024-08-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_first_name_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('need_transportation', 'Need transportation'), ('give_transportation', 'Give Transportation')], max_length=40, null=True),
        ),
    ]
